version: '3'
services:
  taskmate:
    image: taskmate:latest
    ports:
      - '5001:5001'
    volumes:
      - ../instance:/run/instance
    environment:
      - SECRET_KEY=<key>
      - MAIL_SERVER=mailcatcher
      - MAIL_PORT=1025
      - MAIL_USE_TLS=1
      - MAIL_USERNAME=<username>
      - MAIL_PASSWORD=<password>
      - SMTP_ENABLED=True

